# Generated by Django 5.0 on 2023-12-12 09:29

import dish.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dish", "0002_dish_dishimage_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"verbose_name_plural": "dishes"},
        ),
        migrations.AlterField(
            model_name="dish",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=dish.models.dish_icon_file_path,
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=dish.models.region_image_file_path,
            ),
        ),
    ]
