# Generated by Django 5.0 on 2023-12-13 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dish", "0003_alter_dish_options_alter_dish_icon_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="liked_by",
            field=models.ManyToManyField(
                related_name="liked_dishes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
