# Generated by Django 5.0 on 2023-12-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dish", "0004_dish_liked_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="categories",
            field=models.ManyToManyField(
                related_name="dishes", to="dish.category"
            ),
        ),
    ]
